### ISSUE TITLE
An update needed on web-watchdog service 

### ISSUE THREAD

**Issue by gemblerz** [waggle-sensor/beehive-server#13]
When beehive-web service needs to be stopped or restarted, beehive-nginx service also has to be restarted to re-configure communication line between them.

In order to fix it, beehive-web-watchdog service needs to additionally check if external requests work. If not working, the service should restart nginx service as well. Below is the code snippet (See elif statement).
``` bash
[Service]
Environment='CONTAINER=beehive-web'
Environment='NGINX_CONTAINER=beehive-nginx'
Environment='DATA=/mnt'

Restart=always
RestartSec=5

ExecStart=/bin/bash -c ' \
  while [ 1 ] ; do \
    sleep 2m ; \
    if [ $(curl --silent --max-time 10 $(docker inspect --format "{{ .NetworkSettings.Networks.beehive.IPAddress }}" beehive-web) | grep "This is the Waggle Beehive web server." | wc -l) -ne 1 ] ; then \
      docker rm -f ${CONTAINER} ; \
    elif [ $(curl --silent --max-time 10 beehive1.mcs.anl.gov | grep "This is the Waggle Beehive web server." | wc -l) -ne 1 ] ; then \
      docker rm -f ${NGINX_CONTAINER} ; \
    fi \
  done'
```

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #29](https://github.com/waggle-sensor/development/issues/29) via [**ZenHub**](https://www.zenhub.com/)
