### ISSUE TITLE
Error following instructions

### ISSUE THREAD

**Issue by ScottFreeCode** [waggle-sensor/beehive-server#19]
I wanted to try out the Array of Things cloud system, so I tried following the Docker instructions in the readme (`docker pull waggle/beehive-server:latest`, `docker network create beehive`...). I set my `$DATA` directory to `export DATA=${HOME}/waggle`, ran the command to create the client certificate, ran the command to start the server in Docker, ran `./configure`, and then ran `./Server.py`; I got this error:

```txt
2017-07-06 20:38:09,104 - config - INFO - line=72 - RABBITMQ_HOST: beehive-rabbitmq
2017-07-06 20:38:09,104 - config - INFO - line=75 - CASSANDRA_HOST: beehive-cassandra
Traceback (most recent call last):
  File "./Server.py", line 3, in <module>
    from config import *
  File "/usr/lib/waggle/beehive-server/config.py", line 184, in <module>
    with open('/mnt/beehive/beehive-config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/beehive/beehive-config.json'
```

Are there any troubleshooting steps I should try? I am not sure what this `beehive-config.json` file it's missing is.

**Comment by seanshahkarami** [comment]
Hello Scott. Thanks for your interest. Maybe we should have had a bigger warning here - Beehive is _not_ currently ready for redeployments. We're actively working packaging things better to make that easier, though.
